version: '2.4'

services:
  octoprint:
    image: octoprint/octoprint
    restart: unless-stopped
    ports:
      - 80:80
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
      - /dev/video0:/dev/video0
    environment:
      - PUID=0
      - GUID=0
      - ENABLE_MJPG_STREAMER=true
    volumes:
     - octoprint:/octoprint
  
volumes:
  octoprint:
