version: '2.4'

services:
  octoprint:
    build: ./octoprint
    restart: always
    ports:
      - '80:5000'
    privileged: true
    labels:
      io.balena.features.supervisor-api: 1
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
      - /dev/video0:/dev/video0
    environment:
      - PUID=0
      - GUID=0
      - ENABLE_MJPG_STREAMER=true
    volumes:
     - octoprint:/octoprint
     - 'octoprint-data:/data'
     - 'plugins:/usr/local/lib/python3.7/dist-packages'
  
volumes:
  octoprint:
  octoprint-data: { }
  plugins:
