webcam:
  timelapseEnabled: false
  webcamEnabled: false
  ffmpeg: /usr/bin/ffmpeg
  snapshot: http://localhost:8080/?action=snapshot
  stream: /webcam/?action=stream
plugins:
  DisplayLayerProgress:
    showAllPrinterMessages: false
    showHeightInStatusBar: false
    showLayerInStatusBar: false
    showOnBrowserTitle: false
    showOnNavBar: false
    showOnPrinterDisplay: true
  thespaghettidetective:
    auth_token: ${OBICO_TOKEN}
    sentry_opt: in
serial:
  autoconnect: true                                                                                                                     
  baudrate: 0                                                                                                                           
  port: AUTO
